# Generated by Django 5.0.7 on 2024-07-22 07:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='板块')),
                ('dutyUser', models.CharField(max_length=20, verbose_name='责任人')),
            ],
            options={
                'verbose_name': '板块',
                'verbose_name_plural': '板块',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='种类')),
                ('doUser', models.CharField(blank=True, max_length=20, null=True, verbose_name='执行人')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskList.plate', verbose_name='板块')),
            ],
            options={
                'verbose_name': '种类',
                'verbose_name_plural': '种类',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_notice_from', models.CharField(blank=True, max_length=4000, null=True, verbose_name='原通知')),
                ('name', models.CharField(max_length=10, verbose_name='任务')),
                ('to_who', models.CharField(blank=True, max_length=10, null=True, verbose_name='交接人')),
                ('wx_notice_to', models.CharField(blank=True, max_length=4000, null=True, verbose_name='发出通知')),
                ('end_time', models.DateTimeField(verbose_name='截止时间')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('finish_time', models.DateTimeField(null=True, verbose_name='完成时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskList.type', verbose_name='种类')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
    ]
